version: '3.4'

services:
  debtbot:
    image: ${DOCKER_REGISTRY-}debtbot
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: .
      dockerfile: DebtBot/Dockerfile
    depends_on:
      - db
      - rabbit

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: debtbot_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rabbit:
    image: rabbitmq:3
    restart: always
    container_name: debtbot_rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=debtbot
      - RABBITMQ_DEFAULT_PASS=debtbot