version: '3.4'

services:

  debtbot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: DebtBot/Dockerfile

  db:
    ports:
      - '5432:5432'
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
    volumes:
      - ./rabbitdata:/var/lib/rabbitmq