version: '3.4'

services:
  debtbot:
    image: jncchds/debtbot:latest
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      # You can specify both of these or just one of them, deleting the other:  
      - DEFAULT_USER_TELEGRAM_ID=123456789
      - DEFAULT_USER_TELEGRAM_USERNAME=@telegram_username 
    depends_on:
      - db
      - rabbit

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: debtbot_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rabbit:
    image: rabbitmq:3
    restart: always
    container_name: debtbot_rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=debtbot
      - RABBITMQ_DEFAULT_PASS=debtbot