version: '3.4'

services:
  debtbot:
    image: ${DOCKER_REGISTRY-}debtbot
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: .
      dockerfile: DebtBot/Dockerfile

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: debtstoragebot_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
       - ./data:/var/lib/postgresql/data