on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push multi-platform image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./DebtBot/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: jncchds/debtbot:latest
